development:
  adapter: postgresql
  database: techlol_development
  pool: 5
  timeout: 5432
  host: localhost
test:
  adapter: postgresql
  database: techlol_test
  pool: 5
  timeout: 5432
  host: localhost

production:
  adapter: postgresql
  database: techlol_production
  pool: 5
  timeout: 5432
  host: localhost
